name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for making your first issue, I will take a look at it soon!\n\nYour contribution is appreciated! 🎉"
        pr-message: "Thank you for making your first pull request, I will take a look at it soon!\n\nYour contribution is appreciated! 🎉"